import json, os

os.makedirs("notebooks", exist_ok=True)

def code(lines):
    src = [l + "\n" for l in lines[:-1]] + [lines[-1]]
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

def md(lines):
    src = [l + "\n" for l in lines[:-1]] + [lines[-1]]
    return {"cell_type": "markdown", "metadata": {}, "source": src}

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 0,
        "metadata": {
            "colab": {"provenance": []},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"}
        },
        "cells": cells
    }

# ──────────────────────────────────────────────────────────
# DAY 1
# Part 1: Multi-Armed Bandit (unchanged)
# Part 2: Custom 2D Maze Q-Learning (replaces FrozenLake)
# Part 3: Q-Table Heatmap (updated for Maze)
# ──────────────────────────────────────────────────────────
day1_cells = [

md([
    "# RL Teaching — Day 1",
    "**Bandit · 2D Maze Q-Learning · Q-Table Heatmap**",
    "",
    "> 📌 **Before you start:** Go to **File → Save a copy in Drive** to make your own editable copy.",
    "",
    "You don't need to understand every line of code.",
    "Focus on **what changes when you adjust the 🔧 parameters** and re-run the cell."
]),

code([
    "# ── Setup (run this first) ──────────────────────────────────",
    "!pip install matplotlib seaborn numpy --quiet",
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "import seaborn as sns",
    "print('✅ Setup complete!')"
]),

md([
    "---",
    "## Part 1 · Multi-Armed Bandit",
    "",
    "Imagine a row of slot machines. Each machine has a *hidden* probability of giving a reward.",
    "The agent uses **ε-greedy strategy**:",
    "- With probability **ε** → try a random machine *(explore)*",
    "- With probability **1 - ε** → pick the best-known machine *(exploit)*",
    "",
    "### 🔧 Your task",
    "Run the cell with **ε = 0.1**, then change it to **ε = 0.9** and run again.",
    "What is different about the two reward curves?"
]),

code([
    "# ════════════════════════════════════════════",
    "epsilon = 0.1   # 🔧 Try: 0.1 / 0.5 / 0.9",
    "# ════════════════════════════════════════════",
    "",
    "np.random.seed(42)",
    "n_bandits, n_rounds = 5, 500",
    "true_probs = [0.2, 0.5, 0.8, 0.4, 0.6]   # hidden from the agent",
    "",
    "Q = np.zeros(n_bandits)",
    "N = np.zeros(n_bandits)",
    "rewards = []",
    "",
    "for t in range(n_rounds):",
    "    action = np.random.randint(n_bandits) if np.random.random() < epsilon else np.argmax(Q)",
    "    reward = 1 if np.random.random() < true_probs[action] else 0",
    "    N[action] += 1",
    "    Q[action] += (reward - Q[action]) / N[action]",
    "    rewards.append(reward)",
    "",
    "smoothed = np.convolve(rewards, np.ones(30)/30, mode='valid')",
    "plt.figure(figsize=(10, 4))",
    "plt.plot(smoothed, linewidth=2, label=f'epsilon = {epsilon}')",
    "plt.axhline(max(true_probs), color='gray', linestyle='--', label='Best possible reward')",
    "plt.xlabel('Round'); plt.ylabel('Avg Reward (smoothed)')",
    "plt.title(f'epsilon-greedy Bandit  |  epsilon = {epsilon}')",
    "plt.legend(); plt.grid(alpha=0.3); plt.show()",
    "",
    'print(f"Agent best guess : Machine #{np.argmax(Q)} (Q = {max(Q):.2f})")',
    'print(f"Actual best      : Machine #{np.argmax(true_probs)} (p = {max(true_probs):.2f})")'
]),

md([
    "---",
    "## Part 2 · 2D Maze — Q-Learning",
    "",
    "The agent navigates a 5×5 grid maze from **S** (top-left) to **G** (bottom-right).",
    "**#** cells are walls — the agent cannot enter them.",
    "",
    "```",
    "S  .  .  .  .",
    ".  #  .  #  .",
    ".  .  .  .  .",
    ".  #  .  #  .",
    ".  .  .  .  G",
    "```",
    "",
    "**Reward design** (same as Rein Room):",
    "- Reach goal  →  **+1.0**",
    "- Each step   →  **-0.01**  (encourages finding shorter paths)",
    "- Hit a wall  →  **-0.05**  (stay in place)",
    "",
    "Actions: 0 = Up, 1 = Down, 2 = Left, 3 = Right",
    "",
    "### 🔧 Your task",
    "Run with default settings. Then try changing **one parameter at a time**.",
    "After training, look at the heatmap — can you trace a path from S to G?"
]),

code([
    "# ════════════════════════════════════════════",
    "alpha      = 0.5    # 🔧 learning rate    — try: 0.1 / 0.5 / 0.9",
    "gamma      = 0.95   # 🔧 discount factor  — try: 0.5 / 0.95 / 0.99",
    "epsilon    = 0.2    # 🔧 exploration rate — try: 0.05 / 0.2 / 0.5",
    "n_episodes = 1000",
    "# ════════════════════════════════════════════",
    "",
    "# ── Maze definition ─────────────────────────",
    "ROWS, COLS = 5, 5",
    "WALLS = {(1,1), (1,3), (3,1), (3,3)}",
    "START, GOAL = (0,0), (4,4)",
    "ACTIONS = [(-1,0),(1,0),(0,-1),(0,1)]   # Up Down Left Right",
    "ACT_NAMES = ['U','D','L','R']",
    "N_STATES  = ROWS * COLS",
    "N_ACTIONS = 4",
    "",
    "def state_id(r, c): return r * COLS + c",
    "",
    "def step(r, c, a):",
    "    nr, nc = r + ACTIONS[a][0], c + ACTIONS[a][1]",
    "    if nr < 0 or nr >= ROWS or nc < 0 or nc >= COLS or (nr,nc) in WALLS:",
    "        return r, c, -0.05, False   # hit wall",
    "    if (nr, nc) == GOAL:",
    "        return nr, nc, 1.0, True    # reached goal",
    "    return nr, nc, -0.01, False     # normal step",
    "",
    "# ── Q-Learning ──────────────────────────────",
    "Q = np.zeros((N_STATES, N_ACTIONS))",
    "episode_rewards, episode_lengths = [], []",
    "",
    "for _ in range(n_episodes):",
    "    r, c = START",
    "    total, steps, done = 0.0, 0, False",
    "    while not done and steps < 200:",
    "        s = state_id(r, c)",
    "        a = np.random.randint(N_ACTIONS) if np.random.random() < epsilon else np.argmax(Q[s])",
    "        nr, nc, reward, done = step(r, c, a)",
    "        ns = state_id(nr, nc)",
    "        Q[s, a] += alpha * (reward + gamma * np.max(Q[ns]) - Q[s, a])",
    "        r, c, total, steps = nr, nc, total + reward, steps + 1",
    "    episode_rewards.append(total)",
    "    episode_lengths.append(steps)",
    "",
    "window = 50",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4))",
    "ax1.plot(np.convolve(episode_rewards, np.ones(window)/window, mode='valid'), color='steelblue', lw=2)",
    "ax1.set(title=f'Episode Reward | alpha={alpha} gamma={gamma} epsilon={epsilon}',",
    "        xlabel='Episode', ylabel='Total Reward')",
    "ax1.grid(alpha=0.3)",
    "ax2.plot(np.convolve(episode_lengths, np.ones(window)/window, mode='valid'), color='coral', lw=2)",
    "ax2.set(title='Episode Length (fewer steps = better path)', xlabel='Episode', ylabel='Steps')",
    "ax2.grid(alpha=0.3)",
    "plt.tight_layout(); plt.show()",
    "success = sum(1 for r in episode_rewards[-200:] if r > 0)",
    'print(f"Success rate (last 200 episodes): {success/200:.1%}")'
]),

md([
    "---",
    "## Part 3 · Q-Table Heatmap",
    "",
    "The Q-table stores a value for every (cell, direction) pair.",
    "- **Arrow** → the direction the agent currently prefers in that cell",
    "- **Color** → how confident the agent is (brighter = more certain)",
    "",
    "This is the same visualization you see on the Rein Room platform.",
    "",
    "### 🔧 Your task",
    "1. Can you trace a path from **S** to **G** by following the arrows?",
    "2. Change `cell_to_inspect` (row, col) to see Q-values for any specific cell.",
    "3. Which area has the clearest arrows? Which area is still uncertain? Why?"
]),

code([
    "# ════════════════════════════════════════════",
    "cell_to_inspect = (3, 4)   # 🔧 (row, col) — try cells along the path",
    "# ════════════════════════════════════════════",
    "",
    "best_act  = np.argmax(Q, axis=1).reshape(ROWS, COLS)",
    "max_Q_val = np.max(Q, axis=1).reshape(ROWS, COLS)",
    "arrows    = np.vectorize(lambda x: ACT_NAMES[x])(best_act)",
    "",
    "# Mark walls, start, goal",
    "display_label = np.full((ROWS, COLS), '', dtype=object)",
    "display_label[START[0], START[1]] = 'S'",
    "display_label[GOAL[0],  GOAL[1]]  = 'G'",
    "for wr, wc in WALLS:",
    "    display_label[wr, wc] = '#'",
    "    max_Q_val[wr, wc] = np.nan",
    "",
    "# Combine arrow + special label",
    "annot = np.where(display_label != '', display_label, arrows)",
    "",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))",
    "",
    "# Heatmap",
    "sns.heatmap(max_Q_val, annot=annot, fmt='', cmap='YlOrRd',",
    "            linewidths=1, ax=ax1, cbar_kws={'label': 'Max Q-value (confidence)'})",
    "ax1.set(title='Best Action per Cell  (arrow = preferred direction, color = confidence)',",
    "        xlabel='Column', ylabel='Row')",
    "",
    "# Bar chart for selected cell",
    "r_i, c_i = cell_to_inspect",
    "s_i = state_id(r_i, c_i)",
    "q_vals = Q[s_i]",
    "colors = ['#e74c3c','#2ecc71','#3498db','#f39c12']",
    "bars = ax2.bar(ACT_NAMES, q_vals, color=colors)",
    "ax2.set(title=f'Q-values for cell ({r_i},{c_i})',",
    "        xlabel='Action', ylabel='Q-value')",
    "ax2.grid(alpha=0.3, axis='y')",
    "for bar, val in zip(bars, q_vals):",
    "    ax2.text(bar.get_x()+bar.get_width()/2, val+0.005, f'{val:.3f}',",
    "             ha='center', va='bottom', fontsize=11)",
    "plt.tight_layout(); plt.show()",
    'print(f"Cell {cell_to_inspect}: preferred direction = {ACT_NAMES[np.argmax(q_vals)]}")'
]),

]

with open("notebooks/RL_Day1.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb(day1_cells), f, ensure_ascii=False, indent=1)
print("✅ RL_Day1.ipynb written")

# ──────────────────────────────────────────────────────────
# DAY 2
# Part 1: CartPole (unchanged)
# Part 2: Maze — Sparse Reward vs Shaped Reward (replaces FrozenLake slippery)
# ──────────────────────────────────────────────────────────
day2_cells = [

md([
    "# RL Teaching — Day 2",
    "**CartPole · Maze: Reward Design Comparison**",
    "",
    "> 📌 **Before you start:** Go to **File → Save a copy in Drive** to make your own editable copy.",
    "",
    "Focus on **what changes when you adjust the 🔧 parameters** and re-run the cell."
]),

code([
    "# ── Setup ────────────────────────────────────────────────────",
    "!pip install gymnasium matplotlib numpy --quiet",
    "import gymnasium as gym",
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "print('✅ Setup complete!')"
]),

md([
    "---",
    "## Part 1 · CartPole — Continuous State Space",
    "",
    "CartPole: keep a pole balanced on a moving cart.",
    "The state has **4 continuous values** — not grid squares like the maze.",
    "",
    "Q-learning needs *discrete* states, so we divide each dimension into **bins**.",
    "Rein Room does this automatically; here you can see exactly what happens.",
    "",
    "```",
    "State dimension    | Range          | Bins",
    "Cart position      | -2.4  to  2.4  | 10",
    "Cart velocity      | -3.0  to  3.0  | 10",
    "Pole angle         | -0.25 to  0.25 | 10",
    "Pole ang. velocity | -3.0  to  3.0  | 10",
    "Total possible states: 10 x 10 x 10 x 10 = 10,000",
    "```",
    "",
    "### 🔧 Your task",
    "Watch the reward curve. When does improvement start?",
    "Does it ever drop suddenly after improving? Why might that happen?"
]),

code([
    "# ════════════════════════════════════════════",
    "alpha      = 0.5   # 🔧 learning rate    — try: 0.2 / 0.5 / 0.8",
    "gamma      = 0.99  # 🔧 discount factor  — try: 0.9 / 0.99",
    "epsilon    = 0.3   # 🔧 exploration rate — try: 0.1 / 0.3 / 0.5",
    "n_episodes = 500",
    "# ════════════════════════════════════════════",
    "",
    "env    = gym.make('CartPole-v1')",
    "n_bins = 10",
    "bins   = [",
    "    np.linspace(-2.4,  2.4,  n_bins),",
    "    np.linspace(-3.0,  3.0,  n_bins),",
    "    np.linspace(-0.25, 0.25, n_bins),",
    "    np.linspace(-3.0,  3.0,  n_bins),",
    "]",
    "",
    "def discretize(obs):",
    "    return tuple(min(np.digitize(obs[i], bins[i]), n_bins-1) for i in range(4))",
    "",
    "Q      = {}",
    "get_q  = lambda s, a: Q.get((s, a), 0.0)",
    "best_a = lambda s: max(range(2), key=lambda a: get_q(s, a))",
    "episode_rewards, episode_lengths = [], []",
    "",
    "for ep in range(n_episodes):",
    "    obs, _  = env.reset()",
    "    state   = discretize(obs)",
    "    total, steps, done = 0, 0, False",
    "    while not done:",
    "        action = env.action_space.sample() if np.random.random() < epsilon else best_a(state)",
    "        nobs, r, ter, tru, _ = env.step(action)",
    "        done   = ter or tru",
    "        ns     = discretize(nobs)",
    "        old_q  = get_q(state, action)",
    "        nmax   = max(get_q(ns, a) for a in range(2))",
    "        Q[(state, action)] = old_q + alpha * (r + gamma * nmax - old_q)",
    "        state, total, steps = ns, total + r, steps + 1",
    "    episode_rewards.append(total)",
    "    episode_lengths.append(steps)",
    "",
    "window = 30",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4))",
    "ax1.plot(np.convolve(episode_rewards, np.ones(window)/window, mode='valid'), lw=2)",
    "ax1.axhline(195, color='red', linestyle='--', label='Solved threshold (195)')",
    "ax1.set(title=f'CartPole Reward | alpha={alpha} gamma={gamma} epsilon={epsilon}',",
    "        xlabel='Episode', ylabel='Total Reward (max 200)')",
    "ax1.legend(); ax1.grid(alpha=0.3)",
    "ax2.plot(np.convolve(episode_lengths, np.ones(window)/window, mode='valid'), color='orange', lw=2)",
    "ax2.set(title='Episode Length  (longer = better balance)',",
    "        xlabel='Episode', ylabel='Steps')",
    "ax2.grid(alpha=0.3)",
    "plt.tight_layout(); plt.show()",
    'print(f"Q-table entries used : {len(Q):,} / {10**4*2:,} possible")',
    'print(f"Avg reward (last 50) : {np.mean(episode_rewards[-50:]):.1f} / 200")'
]),

md([
    "---",
    "## Part 2 · Maze — Reward Design: Sparse vs. Shaped",
    "",
    "Same 5×5 maze as Day 1. We train the agent **twice** with different reward functions.",
    "",
    "| Version | Reach goal | Each step | Hit wall |",
    "|---------|-----------|-----------|----------|",
    "| **Sparse** (standard) | +1.0 | 0 | 0 |",
    "| **Shaped** (Rein Room style) | +1.0 | -0.01 | -0.05 |",
    "",
    "**Key question:** Why does reward design matter?",
    "- Sparse reward: the agent gets no feedback until it accidentally reaches the goal.",
    "  It may wander for hundreds of episodes before learning anything.",
    "- Shaped reward: the agent gets a small penalty each step, so it learns to",
    "  take shorter paths — feedback is immediate and continuous.",
    "",
    "### 🔧 Your task",
    "Run the cell and compare the two learning curves.",
    "- Which one starts improving earlier?",
    "- Which one finds a shorter path (fewer steps)?",
    "- Why does immediate feedback make learning easier?"
]),

code([
    "# Fixed parameters — focus on comparing reward functions",
    "alpha, gamma, epsilon, n_episodes = 0.5, 0.95, 0.2, 1000",
    "window = 50",
    "",
    "ROWS, COLS = 5, 5",
    "WALLS = {(1,1), (1,3), (3,1), (3,3)}",
    "START, GOAL = (0,0), (4,4)",
    "ACTIONS = [(-1,0),(1,0),(0,-1),(0,1)]",
    "N_STATES, N_ACTIONS = ROWS * COLS, 4",
    "",
    "def state_id(r, c): return r * COLS + c",
    "",
    "def step_maze(r, c, a, shaped):",
    "    nr, nc = r + ACTIONS[a][0], c + ACTIONS[a][1]",
    "    if nr < 0 or nr >= ROWS or nc < 0 or nc >= COLS or (nr,nc) in WALLS:",
    "        reward = -0.05 if shaped else 0.0",
    "        return r, c, reward, False",
    "    if (nr, nc) == GOAL:",
    "        return nr, nc, 1.0, True",
    "    reward = -0.01 if shaped else 0.0",
    "    return nr, nc, reward, False",
    "",
    "def run_maze(shaped):",
    "    Q = np.zeros((N_STATES, N_ACTIONS))",
    "    ep_rewards, ep_lengths = [], []",
    "    for _ in range(n_episodes):",
    "        r, c = START",
    "        total, steps, done = 0.0, 0, False",
    "        while not done and steps < 300:",
    "            s = state_id(r, c)",
    "            a = np.random.randint(N_ACTIONS) if np.random.random() < epsilon else np.argmax(Q[s])",
    "            nr, nc, reward, done = step_maze(r, c, a, shaped)",
    "            ns = state_id(nr, nc)",
    "            Q[s, a] += alpha * (reward + gamma * np.max(Q[ns]) - Q[s, a])",
    "            r, c, total, steps = nr, nc, total + reward, steps + 1",
    "        ep_rewards.append(total)",
    "        ep_lengths.append(steps)",
    "    return ep_rewards, ep_lengths",
    "",
    "print('Training... (~5 seconds)')",
    "r_sparse, l_sparse = run_maze(shaped=False)",
    "r_shaped, l_shaped = run_maze(shaped=True)",
    "",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4))",
    "",
    "for rewards, label, color in [",
    "    (r_sparse, 'Sparse reward (no step penalty)',   'coral'),",
    "    (r_shaped, 'Shaped reward (step penalty -0.01)', 'steelblue'),",
    "]:",
    "    s = np.convolve(rewards, np.ones(window)/window, mode='valid')",
    "    ax1.plot(s, label=label, color=color, lw=2)",
    "ax1.set(title='Episode Reward: Sparse vs. Shaped',",
    "        xlabel='Episode', ylabel='Total Reward')",
    "ax1.legend(); ax1.grid(alpha=0.3)",
    "",
    "for lengths, label, color in [",
    "    (l_sparse, 'Sparse reward', 'coral'),",
    "    (l_shaped, 'Shaped reward', 'steelblue'),",
    "]:",
    "    s = np.convolve(lengths, np.ones(window)/window, mode='valid')",
    "    ax2.plot(s, label=label, color=color, lw=2)",
    "ax2.set(title='Episode Length (fewer steps = better path)',",
    "        xlabel='Episode', ylabel='Steps')",
    "ax2.legend(); ax2.grid(alpha=0.3)",
    "plt.tight_layout(); plt.show()",
    "",
    "sparse_success = sum(1 for r in r_sparse[-200:] if r > 0)",
    "shaped_success = sum(1 for r in r_shaped[-200:] if r > 0)",
    'print(f"Sparse reward — success rate (last 200): {sparse_success/200:.1%}")',
    'print(f"Shaped reward — success rate (last 200): {shaped_success/200:.1%}")'
]),

]

with open("notebooks/RL_Day2.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb(day2_cells), f, ensure_ascii=False, indent=1)
print("✅ RL_Day2.ipynb written")
print("\nDone! Both notebooks saved to notebooks/")
